version: '3'

services:
  ldap_server:
    image: ilyaponomarenko/newldap:test
    container_name: openldap
    ports:
      - 389:389
    environment:
      LDAP_ORGANISATION: Colleague-feedback
      LDAP_DOMAIN: employeesdb.com
      LDAP_BASE_DN: dc=employeesdb,dc=com
      LDAP_ADMIN_PASSWORD: secret
      
  ldap_server_admin:
    image: osixia/phpldapadmin:0.9.0
    container_name: ldap_server_admin
    ports:
      - "8080:80"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap_server
      PHPLDAPADMIN_HTTPS: "false"

volumes:
  ldap_data:
  ldap_config:
